version: '3'
services:

  postgres:
    image: registry.gitlab.com/basemate-ops/workflow/postgres
    expose:
      - 5432
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development

  rails:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      RAILS_ENV: "development"
      POSTGRES_DB: "development"
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
      - node-volume:/app/node_modules
    command: "bundle exec rails server --binding 0.0.0.0 --port 3000"

volumes:
  data-volume:
  gem-volume:
  node-volume:
