version: '3'
services:

  postgres:
    image: registry.gitlab.com/basemate-ops/workflow/postgres
    expose:
      - 5432
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "production"
    env_file:
      - ./.env

  rails:
    image: registry.gitlab.com/matestack/matestack-docs
    ports:
      - "3001:3000"
    links:
      - postgres
    environment:
      RAILS_ENV: "production"
      POSTGRES_DB: "production"
      DOCS_RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    env_file:
      - ./.env
    command: "bundle exec rails server --binding 0.0.0.0 --port 3000"

volumes:
  data-volume:
