default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: matestack_docs_development

test:
  <<: *default
  database: matestack_docs_test

production:
  <<: *default
  database: matestack_docs_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
